quizmaster/quiz/urls.py
from django.urls import path
from . import views
from .views import quiz_list, user_profile

app_name = "quiz"

urlpatterns = [
    path('register/', views.register_user, name="register_user"),
    path('login/', views.login_user, name="login_user"),
    path('list/', views.quiz_list, name="quiz_list"),
    path('<int:quiz_id>/', views.detail, name="detail"),
    path('new/', views.create_quiz, name="create_quiz"),
    path('<int:quiz_id>/edit/', views.edit_quiz, name="edit_quiz"),
    path('<int:quiz_id>/delete/', views.delete_quiz, name="delete_quiz"),
    path('<int:quiz_id>/question/new', views.create_question, name="create_question"),
    path('<int:question_id>/question/delete/', views.delete_question, name="delete_question"),
    path('<int:question_id>/question/', views.question_detail, name="question_detail"),
    path('<int:quiz_id>/comments/new/', views.post_comment, name="post_comment"),
    path("<int:comment_id>/comments/delete/", views.delete_comment, name="delete_comment"),
    path("<int:quiz_id>/like/", views.like_quiz, name="like"),
    path("<int:quiz_id>/solve/", views.solve_quiz, name="solve_quiz"),
    path("<int:quiz_id>/solve/result/", views.submit_quiz, name="submit_quiz"),
    path("<int:quiz_id>/solve/results/<int:result_id>/", views.result_quiz, name="result_quiz"),
    path('<int:user_id>/profile/', views.user_profile, name="user_profile"),
]

quizmaster/quizmaster/urls.py
from django.contrib import admin
from django.urls import path, include

from quiz import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name="home_path"),
    path('quiz/', include("quiz.urls")),
    path('accounts/', include("django.contrib.auth.urls"))
]

quizmaster/quiz/models.py
from django.db import models
from django.contrib.auth.models import User

class Account(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    moderator = models.BooleanField()

    def __str__(self):
        return f"{self.user.username}, is_moderator:{self.moderator}"

class Quiz(models.Model):
    quiz_name = models.CharField(max_length=200, blank=False)
    pub_date = models.DateTimeField("date published", auto_now_add=True)
    description = models.TextField(blank=False)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.quiz_name
    
    def liked_by(self, user):
        try:
            return self.likes.filter(user=user).count() > 0
        except:
            return False
        
    def toggle_like(self, user):
        if self.likes.filter(user=user).count() > 0:
            like = self.likes.filter(user=user)
            like.delete()
        else:
            like = self.likes.create(user=user)
   
class Question(models.Model):
    question_text = models.CharField(max_length=200, blank=False)
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)

    def __str__(self):
        return self.question_text

class Answer(models.Model):
    answer_text = models.CharField(max_length=200, blank=False)
    is_correct = models.BooleanField()
    question = models.ForeignKey(Question, on_delete=models.CASCADE)

    def __str__(self):
        return self.answer_text

class Comment(models.Model):
    comment_text = models.TextField(blank=False)
    pub_date = models.DateTimeField("date published", auto_now_add=True)
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE, related_name='comments')
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.comment_text

class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE, related_name="likes")

    def __str__(self):
        return f"{self.user.username} likes {self.quiz.quiz_name}"

class QuizResult(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    score = models.IntegerField(blank=False)
    correct_answers = models.IntegerField(blank=False)

class Choice(models.Model):
    correct = models.BooleanField()
    answer = models.ForeignKey(Answer, on_delete=models.CASCADE)
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    current_quiz = models.ForeignKey(QuizResult, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.question.question_text} in quiz {self.quiz.quiz_name} answered {self.correct}"

quizmaster/quiz/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.decorators import login_required

from .models import Quiz, Question, Answer, Comment, Choice, QuizResult, Account

from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login

from django.urls import reverse

import logging
logger = logging.getLogger('django')
# Create your views here.
def home(request):

    return render(request, 'quiz/home.html')

def register_user(request):

    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        repeat_password = request.POST['repeat-password']

        does_exist = User.objects.filter(username=username).exists()

        if does_exist is False:
            if password == repeat_password:
                user = User.objects.create_user(username = username, password = password)
                account = Account(user=user, moderator=False)
                user.save()
                account.save()
                # odma nakon registracije logiramo korisnika
                new_user = authenticate(username=username, password=password)
                login(request, new_user)
                return HttpResponseRedirect('/')
            else:
                context = {
                    'error': "Passwords don't match"
                }
                return render(request, 'registration/register.html', context)
        else:
            context = {
                'error': "User with that username already exists"
            }
            return render(request, 'registration/register.html', context)
            
    return render(request, 'registration/register.html')

def login_user(request):

    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return HttpResponseRedirect('/')
        else:
            context = {
                'error': "Invalid credentials"
            }
        
            return render(request, 'registration/login.html', context)
    
    return render(request, 'registration/login.html')

def quiz_list(request):

    context = {}
    quizzes = Quiz.objects.all()

    context = {
        "quizzes": quizzes
    }

    return render(request, 'quiz/list.html', context)

def detail(request, quiz_id):
    context = {}

    quiz = get_object_or_404(Quiz,pk=quiz_id)
    context = {
        "quiz": quiz,
        "liked": quiz.liked_by(request.user)
    }

    return render(request, 'quiz/quiz_detail.html', context)

def create_quiz(request):

    if request.method == "POST" and request.user.is_authenticated:
        title = request.POST["title"]
        description = request.POST["description"]
        quiz = Quiz(quiz_name=title, description=description, author=request.user)
        quiz.save()
        
        return HttpResponseRedirect(reverse('quiz:edit_quiz', args=[quiz.id, ]))
    
    return render(request, 'quiz/create_quiz.html')

def delete_quiz(request, quiz_id):

    if request.method == "POST" and request.user.is_authenticated:
        quiz = get_object_or_404(Quiz, pk=quiz_id)
        quiz.delete()

        return render(request, 'quiz/home.html')
    
def edit_quiz(request, quiz_id):
    quiz = get_object_or_404(Quiz, pk=quiz_id)

    context = {
        "quiz": quiz,
        "range": range(1, 5)
    }
        
    return render(request, 'quiz/edit_quiz.html', context)

def create_question(request, quiz_id):

    quiz = get_object_or_404(Quiz, pk=quiz_id)

    if request.method == "POST" and request.user.is_authenticated:
        title = request.POST["title"]
        question = Question(question_text=title, quiz=quiz)
        
        question.save()

        for i in range(1, 5):
            curr_ans = request.POST["answer_" + str(i)]
            if request.POST["radio_button"] == "radio_answer_" + str(i):
                is_corr = True
            else:
                is_corr = False
            answer = Answer(answer_text=curr_ans, is_correct=is_corr, question=question)
            answer.save()

        return HttpResponseRedirect(reverse('quiz:edit_quiz', args=[quiz.id, ]))

def delete_question(request, question_id):

    if request.method == "POST" and request.user.is_authenticated:
        question = get_object_or_404(Question, pk=question_id)
        question.delete()

        return HttpResponseRedirect(reverse('quiz:edit_quiz', args=[question.quiz.id, ]))

def question_detail(request, question_id):
    context = {}

    question = get_object_or_404(Question, pk=question_id)
    context = {
        "question": question
    }

    return render(request, 'quiz/question_detail.html', context)


def post_comment(request, quiz_id):
    quiz = get_object_or_404(Quiz, pk=quiz_id)
    if request.method == "POST" and request.user.is_authenticated:
        comment = Comment(
            user = request.user,
            comment_text=request.POST['comment_text'],
            quiz=quiz
        )
        comment.save()

    return HttpResponseRedirect(reverse("quiz:detail", args=[quiz_id,]))

def delete_comment(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    quiz = get_object_or_404(Quiz, pk=comment.quiz.id)

    if request.method == "POST" and request.user.is_authenticated:
        comment.delete()

        return HttpResponseRedirect(reverse("quiz:detail", args=[quiz.id, ])) 

def like_quiz(request, quiz_id):
    quiz = get_object_or_404(Quiz, id=quiz_id)

    if request.method == 'POST' and request.user.is_authenticated:
        quiz.toggle_like(request.user)
        
    return HttpResponseRedirect(reverse("quiz:detail", args=[quiz_id,]))

def solve_quiz(request, quiz_id):
    quiz = get_object_or_404(Quiz, pk=quiz_id)

    context = {
        "quiz": quiz,
    }

    return render(request, 'quiz/quiz_solve.html', context)

def submit_quiz(request, quiz_id):
    quiz = get_object_or_404(Quiz, pk=quiz_id)

    if request.method == 'POST' and request.user.is_authenticated:
        questions = quiz.question_set.all()
        quiz_result = QuizResult(user=request.user, quiz=quiz, score=0, correct_answers=0)
        quiz_result.save()

        for question in questions:
            correct_answer = question.answer_set.get(is_correct=True)
            current_choice = request.POST["radio-" + str(question.id)]
            current_answer = question.answer_set.get(pk=int(current_choice))

            if int(current_choice) == correct_answer.id:
                quiz_result.correct_answers += 1
                choice = Choice(correct=True, quiz=quiz, current_quiz=quiz_result, question=question, answer=current_answer)
                quiz_result.save()
                choice.save()
            else:
                choice = Choice(correct=False, quiz=quiz, current_quiz=quiz_result, question=question, answer=current_answer)
                choice.save()
    
        return HttpResponseRedirect(reverse('quiz:result_quiz', args=[quiz_id, quiz_result.id, ]))
    else:
        return HttpResponseRedirect(reverse('quiz:solve_quiz', args=[quiz_id, ]))
    
def result_quiz(request, quiz_id, result_id):
    
    quiz = get_object_or_404(Quiz, pk=quiz_id)
    result = get_object_or_404(QuizResult, pk=result_id)

    questions = quiz.question_set.all()
    choices = result.choice_set.all()

    questions_count = quiz.question_set.count()
    score = (result.correct_answers / questions_count) * 100

    result.score = round(score, 2)
    result.save()

    content = []
    
    for i in range(questions_count):
        content.append({
            "question": questions[i],
            "choice": choices[i],
            "correct": questions[i].answer_set.get(is_correct=True)
        })

    context = {
        "quiz": quiz,
        "result": result,
        "content": content,
    }

    return render(request, 'quiz/quiz_result.html', context)

def user_profile(request, user_id):
    user_profile = get_object_or_404(User, pk=user_id)
    
    quiz_results = QuizResult.objects.filter(user=user_profile)
    created_quizzes = Quiz.objects.filter(author=user_profile)
    
    total_percentage = 0
    for result in quiz_results:
        total_percentage += result.score
    
    if total_percentage > 0 and quiz_results.count() > 0:
        average_percentage = total_percentage / quiz_results.count()
    else:
        average_percentage = 0

    context = {
        'user_profile': user_profile,
        'quiz_results': quiz_results,
        'average_percentage': round(average_percentage, 2),
        'created_quizzes': created_quizzes
    }

    return render(request, 'quiz/user_profile.html', context)

quizmaster/quiz/templates/quiz/base.html
{% load static %}

<html>
    <head>
        <title>Quiz Master</title>
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">

        <link rel="stylesheet" href="{% static 'quiz/css/base.css' %}">
        <link rel="stylesheet" href="{% static 'quiz/css/home.css' %}">
        <link rel="stylesheet" href="{% static 'quiz/css/quiz_list.css' %}">
        <link rel="stylesheet" href="{% static 'quiz/css/quiz_detail.css' %}">
        <link rel="stylesheet" href="{% static 'quiz/css/quiz_create.css' %}">
        <link rel="stylesheet" href="{% static 'quiz/css/quiz_edit.css' %}">
        <link rel="stylesheet" href="{% static 'quiz/css/quiz_solve.css' %}">
        <link rel="stylesheet" href="{% static 'quiz/css/solve_result.css' %}">
        <link rel="stylesheet" href="{% static 'quiz/css/question_detail.css' %}">
        <link rel="stylesheet" href="{% static 'quiz/css/user_profile.css' %}">
        <link rel="stylesheet" href="{% static 'registration/css/registration.css' %}">
    </head>
    <body>
        <header class="header">
            <div class="header-brand">
                <h1>
                    <a href="/" class="home-link">QuizMaster</a>
                </h1>
            </div>
            <nav class="header-nav">
                {% if request.user.is_superuser %}
                    <a class="admin-link" href="/admin">Go to admin</a>
                {% endif %}
                {% if request.user.is_authenticated %}
                    <p class="nav-username">User:
                        <a href="{% url 'quiz:user_profile' request.user.id %}" class="author-link"> 
                            {{ request.user.username }}
                        </a>
                    </p>
                    <form method="post" action="{% url 'logout' %}" class="logout-form">
                        {% csrf_token %}
                        <button type="submit">Logout</button>
                    </form>
                {% else %}
                    <a href="{% url 'quiz:login_user' %}" class="login-link">
                        Login
                    </a>
                    <a href="{% url 'quiz:register_user' %}" class="login-link">
                        Register
                    </a>
                {% endif %}
            </nav>
        </header>
        <div class="main-content">
            {% block content %}
            {% endblock %}
        </div>
    </body>
</html>

quizmaster/quiz/templates/quiz/create_quiz.html
{% extends "quiz/base.html" %}
{% block content %}

{% if request.user.is_authenticated %}
<div class="quiz-create-layout">
    <div class="quiz-create-header">
        <h1>Create a quiz</h2>
    </div>
    <form method="post" action="{% url 'quiz:create_quiz' %}" class="quiz-create-form">
        {% csrf_token %}
        <input type="text" id="title" name="title" placeholder="Quiz name" class="quiz-create-title" required>
        <textarea 
            id="description" 
            name="description" 
            placeholder="Quiz description"
            cols=30
            rows=7
            required
            class="quiz-create-desc"
        ></textarea>
        <div class="create-button-div">
            <button type="submit" class="list-item-button">Create</button>
        </div>
    </form>
</div>
{% else %}
    <p>You have to be logged in to create a quiz</p>
{% endif %}
{% endblock content %}

quizmaster/quiz/templates/quiz/edit_quiz.html
{% extends "quiz/base.html" %}
{% block content %}

{% if request.user.is_authenticated %}
<div class="quiz-edit-layout">
    <div class="quiz-edit-header">
        <h2>Add question for: {{ quiz.quiz_name }}</h2>
    </div>
    <div class="existing-questions">
        <p>Existing questions: </p>
    </div>
    {% for question in quiz.question_set.all %}
        <div class="exquestion-container">
            <div class="exquestion-content">
                <a href="{% url 'quiz:question_detail' question.id %}">{{ question.question_text }}</a>
            </div>
            {% if request.user == quiz.author or request.user.account.moderator == True %}
                <form method="post" action="{% url 'quiz:delete_question' question.id %}" class="exquestion-delete">
                    {% csrf_token %}
                    <button type="submit">Delete</button>
                </form>
            {% endif %}
        </div>
    {% endfor %}
    <form method="post" action="{% url 'quiz:create_question' quiz.id %}" class="add-question-form">
        <h2>Add a question</h2>
        {% csrf_token %}
        <div class="add-question-title">
            <input type="text" name="title" placeholder="Question text" required>
        </div>
        <div class="add-answers-container">
            {% for i in range %}
                <input type="text" name="answer_{{i}}" placeholder="Answer no. {{i}}" required class="answer-text">
            {% endfor %}
        </div>
        <div class="correct-answers-container">
            <p>Select the correct answer</p>
            {% for i in range %}
                <div class="correct-answers-item">
                    <span>{{i}}.</span>
                    <input type="radio" name="radio_button" value="radio_answer_{{i}}" required>
                </div>
            {% endfor %}
        </div>
        <div class="add-question-button-div">
            <button type="submit" class="list-item-button">Add</button>
        </div>
    </form>
    {% if request.user.account.moderator == True or quiz.author == request.user %}
        <form method="post" action="{% url 'quiz:delete_quiz' quiz.id %}" class="quiz-delete-form">
            {% csrf_token %}
            <button type="submit">Delete quiz</button>
        </form>
    {% endif %}
</div>
{% else %}
    <p>You have to be logged in to create a quiz</p>
{% endif %}
{% endblock content %}

quizmaster/quiz/templates/quiz/home.html
{% extends 'quiz/base.html' %}
{% block content %}

<div class="home-layout">
    <header class="home-header">
        <h1>Quiz Master</h1>
        <p>Welcome to quiz master</p>
    </header>
    <div class="home-main">
        <h2>Solve quizzes or create your own</h2>
        <div class="link-container">
            <a href="{% url 'quiz:quiz_list' %}">
                <button>All Quizzes</button>
            </a>
        </div>
        <div class="link-container">
            <a href="{% url 'quiz:create_quiz' %}">
                <button>Create your own Quiz</button>
            </a>
        </div> 
    </div>
</div>


{% endblock content %}

quizmaster/quiz/templates/quiz/list.html
{% extends 'quiz/base.html' %}
{% block content %}


<div class="quiz-list-layout">
    <h1 class="quiz-list-heading">All Quizzes</h1>
{% for quiz in quizzes %}
    <div class="quiz-list-item">
        <h2 class="list-item-heading">
            <a href="{% url 'quiz:detail' quiz.id %}">{{ quiz.quiz_name }}</a>
        </h2>
        <div class="list-item-info">
            <!-- link na profil treba napravit jednog dana -->   
            <p>Author: 
                <a href="{% url 'quiz:user_profile' quiz.author.id %}" class="author-link">{{ quiz.author }}</a>
            </p>
            <p>Made at: <span style="font-weight: bold;">{{ quiz.pub_date }}</span></p>
            <p>Number of questions: <span style="font-weight: bold;">{{ quiz.question_set.count }}</span></p>
            <p>Likes: <span style="font-weight: bold;">{{ quiz.likes.count }}</span></p>
            <p>Comments: <span style="font-weight: bold;">{{ quiz.comments.count }}</span></p>
        </div>
        <!-- href treba promjenit kad napravimo view za rješavanje kviza -->
        <div class="list-item-button-div">
            <a href="{% url 'quiz:solve_quiz' quiz.id %}"> 
                <button class="list-item-button">Play Now</button>
            </a>
        </div>
    </div>
{% endfor %}
</div>

{% endblock content %}

quizmaster/quiz/templates/quiz/question_detail.html
{% extends "quiz/base.html" %}
{% block content %}

{% if question.quiz.author == request.user or request.user.account.moderator == True %}

<div class="question-detail-layout">
    <h3>{{ question.question_text }}</h3>
    <div class="question-detail-answers">
        {% for answer in question.answer_set.all %}
            <div class="question-detail-answers-item">
                {% if answer.is_correct %}
                    <p style="color:#90ee90;">{{ answer.answer_text }}</p>
                {% else %}
                    <p>{{ answer.answer_text }}</p>
                {% endif %}
            </div>
        {% endfor %}
    </div>
        <a href="{% url 'quiz:edit_quiz' question.quiz.id %}">
            <button class="list-item-button">Edit quiz</button>
        </a>
</div>
{% else %}
<div class="question-detail-layout">
    <h3>You have to be the quiz author to see this page</h3>
</div>
{% endif %}
{% endblock content %}

quizmaster/quiz/templates/quiz/quiz_detail.html
{% extends "quiz/base.html" %}
{% block content %}

<div class="quiz-detail-layout">
    <div class="quiz-detail-heading">
        <h1>{{ quiz.quiz_name }}</h1>
    </div>
    <div class="quiz-detail-info">
        <p>Made at: <span style="font-weight: bold;">{{ quiz.pub_date }}</span></p>
        <p>Author: 
            <a href="{% url 'quiz:user_profile' quiz.author.id %}" class="author-link">{{ quiz.author }}</a>
        </p>
        <p>Number of questions: <span style="font-weight: bold;">{{ quiz.question_set.count }}</span></p>
        <p>Likes: <span style="font-weight: bold;">{{ quiz.likes.count }}</span></p>
        <p>Comments: <span style="font-weight: bold;">{{ quiz.comments.count }}</span></p>
    </div>
    <div class="detail-button-div">
        <!-- promjenit href na rjesavanje kviza kad se napravi-->
        <a href="{% url 'quiz:solve_quiz' quiz.id %}">
            <button class="list-item-button">Play Now</button>
        </a>
        <form method="post" action="{% url 'quiz:like' quiz.id %}" class="like-form">
            {% csrf_token %}
            {% if liked %}
                <button type="submit" class="list-item-button">Unlike</button>
            {% else %}
                <button type="submit" class="list-item-button">Like</button>
            {% endif %}
        </form>
    </div>
    <div class="quiz-detail-desc">
        <h2 class="quiz-desc-heading">Quiz description: </h2>
        <p>{{ quiz.description }}</p>
    </div>
</div>

{% if request.user.account.moderator == True or quiz.author == request.user %}
    <div class="quiz-detail-questions">
        <h2>Questions: </h2>
        {% for question in quiz.question_set.all %}
            <p class="detail-question-heading">{{ question.question_text }}?</p>
            <div class="quiz-detail-answers">
                {% for answer in question.answer_set.all %}
                    <div class="detail-answers-item">
                        <p>{{ answer.answer_text }}</p>
                        {% if answer.is_correct == True %}
                            <p style="color: #FFC300;">Correct</p>
                        {% endif %}
                    </div>
                {% endfor %}
            </div>
        {% endfor %}
        <div class="questions-button-div">
            <a href="{% url 'quiz:edit_quiz' quiz.id %}">
                <button class="list-item-button">Edit quiz</button>
            </a>
        </div>
    </div>
{% endif %}

<div class="comments-layout">
    <h1 class="comments-heading">Comments</h1>
    <div class="comments-container">
        {% for comment in quiz.comments.all %}
            <div class="comment-item">
                <div class="comment-item-header">
                    <p>@{{ comment.user.username }}</p>
                    <p class="comment-date">{{ comment.pub_date }}</p>
                    {% if comment.user == request.user or request.user.account.moderator == True %}
                        <form method="POST" action="{% url 'quiz:delete_comment' comment.id %}">
                            {% csrf_token %}
                            <button type="submit">Delete</button>
                        </form>
                    {% endif %}
                </div>
                <div class="comment-item-content">
                    <p>{{ comment.comment_text }}</p>
                </div>
            </div>
        {% endfor %}
    </div>
    {% if request.user.is_authenticated %}
        <form action="{% url 'quiz:post_comment' quiz.id %} " method="post" class="comment-form">
            {% csrf_token %}
            <input id="comment_text" name="comment_text" type="text" placeholder="Enter your comment here">
            <div class="comment-btn-div">
                <button type="submit" class="list-item-button">Submit</button>
            </div>
        </form>
    {% else %}
        <p class="comment-login">You have to be logged in to comment |
            <a href="{% url 'login' %}">Login</a>
        </p>
    {% endif %}
   
</div>

{% endblock content %}

quizmaster/quiz/templates/quiz/quiz_result.html
{% extends 'quiz/base.html' %}
{% block content %}
<div class="solve-layout">
    <div class="solve-heading">
        <h1>Quiz Result</h1>
    </div>
    <div class="result-info">
        <p>Quiz name: <span style="font-weight:bold;">{{ quiz.quiz_name }}</span></p>
        <p>Correct answers: 
            <span style="font-weight:bold;">{{ result.correct_answers }} / {{ quiz.question_set.count }}</span>
        </p>
        <p>Final score: <span style="font-weight:bold;">{{ result.score }} %</span></p>
    </div>
    <div class="result-content">
        {% for item in content %}
            <div class="result-item">
                <div class="result-item-heading">
                    <h3 style="font-weight:normal;">Question: 
                        <span style="font-weight:bold;">{{ item.question.question_text }}</span>
                    </h3>
                </div>
                <div class="result-item-content">
                    {% for answer in item.question.answer_set.all %}
                        <div class="item-answer-result">
                            {% if answer.is_correct %}
                                <p style="color:#90ee90;">{{ answer.answer_text }}</p>
                            {% else %}
                                <p>{{ answer.answer_text }}</p>
                            {% endif %}
                        </div>
                    {% endfor %}
                </div>
                <p class="result-user-answer">User answered:
                    {% if item.choice.correct == True %}
                        <span style="color:#90ee90;">{{ item.choice.answer.answer_text }}</span>
                    {% else %}
                        <span style="color:red;">{{ item.choice.answer.answer_text }}</span>
                    {% endif %}
                </p>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock content %}

quizmaster/quiz/templates/quiz/quiz_solve.html
{% extends "quiz/base.html" %}
{% block content %}

{% if request.user.is_authenticated %}
<div class="solve-layout">
    <div class="solve-heading">
        <h1 style="font-weight: normal;">Solving quiz: <span style="font-weight:bold;">{{ quiz.quiz_name }}</span></h1>
    </div>
    <form method="post" action="{% url 'quiz:submit_quiz' quiz.id %}" class="solve-form">
        {% csrf_token %}
        {% for question in quiz.question_set.all %}
            <div class="solve-form-heading">
                <h2>{{ question.question_text }}</h2>
            </div>
            <div class="solve-form-content">
                {% for answer in question.answer_set.all %}
                    <div class="solve-answer">
                        <p>{{ answer.answer_text }}</p>
                        <input type="radio" name="radio-{{question.id}}" value="{{answer.id}}" required>
                    </div>
                {% endfor %}
            </div>
        {% endfor %}
        <button type="submit" class="list-item-button">Submit answers</button>
    </form>
</div>

{% else %}
<p>You have to be logged in to solve a quiz. <a href="{% url 'login' %}">Login here</a></p>
{% endif %}

{% endblock content %}